sudo: required
dist: trusty

language: ruby

script:
  - bundle exec rake test_app
  - travis_retry bundle exec rake spec

env:
  - DB=mysql
  - DB=postgres

rvm:
  - 2.5.3
  - 2.6.1

gemfile:
  - gemfiles/spree_3_7.gemfile
  - gemfiles/spree_master.gemfile

before_install:
  - mysql -u root -e "GRANT ALL ON *.* TO 'travis'@'%';"

matrix:
  exclude:
    - rvm: 2.5.3
      gemfile: gemfiles/spree_master.gemfile
    - rvm: 2.6.1
      gemfile: gemfiles/spree_3_7.gemfile

  allow_failures:
        - gemfile: gemfiles/spree_master.gemfile
